Start anagrams project 
//Start of anagram project 
import java.io*;
import java.util*;

public class anagrams{
        public static String signature(String word){
                char[]letters=word.toCharArray();
                        Arrays.sort(letters);
                                return new string(letters);

                                    }
                                        public static void main(String []args){
                                                String inputFile =("joyce1922_ulysses.text");
                                                        File file=new File(inputFile);

                                                                // check if file exisits 
                                                                        if(!file.exisits()){
                                                                                    System.out.println("ERROR:File not found ->" + inputFile);
                                                                                                return;

                                                                                                        }
                                                                                                                //Map storing word counts 
                                                                                                                        Map <String,Integer> wordCount =new TreeMap<>();
                                                                                                                                
                                                                                                                                        // Map storing anagram groups
                                                                                                                                                Map <String,ArrayList<String>>anagramGroups =new TreeMap<>();


                                                                                                                                                        try(BufferedReader reader =new BufferedReader(new FileReader(file))){
                                                                                                                                                                    String line;
                                                                                                                                                                                while((line=reader.readline()) !=null){
                                                                                                                                                                                                String [] words =line.split("\\s+");
                                                                                                                                                                                                                for (String w: words){
                                                                                                                                                                                                                                    // cleaning of words but keep apostrophes
                                                                                                                                                                                                                                                        String clean = w.replaceAll("^[^a-zA-Z']+","");
                                                                                                                                                                                                                                                                            clean=clean.replaceAll("[^a-zA-Z']+$","");
                                                                                                                                                                                                                                                                                                clean =clean.toLowerCase();
                                                                                                                                                                                                                                                                                                                    if(clean.length()==0){
                                                                                                                                                                                                                                                                                                                                            continue(); 
                                                                                                                                                                                                                                                                                                                                                                    wordCount.getOrDefault((clean,0)+1);
                                                                                                                                                                                                                                                                                                                                                                                            
                                                                                                                                                                                                                                                                                                                                                                                                                    } 
                                                                                                                                                                                                                                                                                                                                                                                                                        }
                                                                                                                                                                                                                                                                                                                                                                                                                                               
                                                                                                                                                                                                                                                                                                                                                                                                                                                   }catch(Exception e){
                                                                                                                                                                                                                                                                                                                                                                                                                                                           e.printStackTrace();
                                                                                                                                                                                                                                                                                                                                                                                                                                                               }
                                                                                                                                                                                                                                                                                                                                                                                                                                                                   for(String word : wordCount.keySet()){
                                                                                                                                                                                                                                                                                                                                                                                                                                                                           String sig= signiture (word);
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                   if(anagramGroups.containsKey(sig)){
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                               anagramGroups.put(sig,new ArrayList<>());
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                           anagramsGroups.get(sig).add(word);

                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                   }
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                           List<String> lines =new ArrayList<>();
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                   for(ArrayList<String> list :anagramGroups.values()){
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                               if(list.size()>1){
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                               Collections.sort(list);
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                               String lineOut =String.join("",list);
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                               lines.add(lineOut + "\\\\");
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                               String rotated=lineOut;

                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                           }for( int i =0;i<list.size()-1;i++){
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                           int space=rotated.indexOf(" ");
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                           rotated= rotated.substring(space+1) +" " +rotated.substring(0,space);
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                           lines.add(rotated + "\\\\");

                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                       }
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                               }
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                   }File dir =new File("latex");
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                       if(!dir.exixsts()){
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                               dir.mkdir();

                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                   }

                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                       }
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                          
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                          }
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                      }
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                              }


                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                  
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                  
}